name: Deploy to Cloud Functions

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: |
          echo "$github.ref"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install firebase-tools
        run: npm install -g firebase-tools
      - name: create .env file
        run: echo "${{secrets.DOT_ENV}}" > .env
      - name: Deploy
        run: |
          npm ci
          npm run build
          npm run deploy --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
